[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.43", features = ["lazy", "parquet", "csv"] }
anyhow = "1"
time = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
